// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Rentify.Services.Migrations
{
    [DbContext(typeof(RentifyDbContext))]
    partial class RentifyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Rentify.Services.Database.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateAppointment")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<int>("PropertyId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.HasIndex("UserId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("Rentify.Services.Database.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateToPay")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPayed")
                        .HasColumnType("boolean");

                    b.Property<int>("MonthNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<int>("PropertyId")
                        .HasColumnType("integer");

                    b.Property<string>("StripePaymentIntentId")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("WarningDateToPay")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("YearNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.HasIndex("UserId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Bez komentara",
                            DateToPay = new DateTime(2025, 12, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsPayed = true,
                            MonthNumber = 12,
                            Name = "Plaćanje mjesečne rate za 12.2025",
                            PaymentStatus = "Pending",
                            Price = 1550.0,
                            PropertyId = 1,
                            UserId = 2,
                            WarningDateToPay = new DateTime(2025, 12, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            YearNumber = 2025
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Bez komentara",
                            DateToPay = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsPayed = true,
                            MonthNumber = 1,
                            Name = "Plaćanje mjesečne rate za 1.2026",
                            PaymentStatus = "Pending",
                            Price = 1550.0,
                            PropertyId = 1,
                            UserId = 2,
                            WarningDateToPay = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            YearNumber = 2026
                        },
                        new
                        {
                            Id = 3,
                            Comment = "Bez komentara",
                            DateToPay = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsPayed = true,
                            MonthNumber = 2,
                            Name = "Plaćanje mjesečne rate za 2.2026",
                            PaymentStatus = "Pending",
                            Price = 1550.0,
                            PropertyId = 1,
                            UserId = 2,
                            WarningDateToPay = new DateTime(2026, 2, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            YearNumber = 2026
                        },
                        new
                        {
                            Id = 5,
                            Comment = "Bez komentara",
                            DateToPay = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsPayed = false,
                            MonthNumber = 0,
                            Name = "Plaćanje kratkog boravka",
                            PaymentStatus = "Pending",
                            Price = 400.0,
                            PropertyId = 8,
                            UserId = 2,
                            WarningDateToPay = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            YearNumber = 0
                        });
                });

            modelBuilder.Entity("Rentify.Services.Database.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActiveOnApp")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRentingPerDay")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumberOfsquares")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("PricePerDay")
                        .HasColumnType("double precision");

                    b.Property<double>("PricePerMonth")
                        .HasColumnType("double precision");

                    b.Property<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Sarajevo",
                            Details = "Bright apartment in central Sarajevo.",
                            IsActiveOnApp = true,
                            IsAvailable = true,
                            IsRentingPerDay = true,
                            Location = "Zmaja od Bosne 12",
                            Name = "Central City Apartment",
                            NumberOfsquares = "55",
                            PricePerDay = 65.0,
                            PricePerMonth = 1550.0,
                            Tags = new List<string> { "urban", "bright", "central", "modern" },
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            City = "Sarajevo",
                            Details = "Flat near the old town.",
                            IsActiveOnApp = true,
                            IsAvailable = true,
                            IsRentingPerDay = true,
                            Location = "Bistrik 7",
                            Name = "Old Town Flat",
                            NumberOfsquares = "48",
                            PricePerDay = 60.0,
                            PricePerMonth = 1450.0,
                            Tags = new List<string> { "historic", "authentic", "warm" },
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            City = "Sarajevo",
                            Details = "Apartment with city views.",
                            IsActiveOnApp = true,
                            IsAvailable = true,
                            IsRentingPerDay = true,
                            Location = "Alipašina 42",
                            Name = "Hillside View Apartment",
                            NumberOfsquares = "60",
                            PricePerDay = 70.0,
                            PricePerMonth = 1650.0,
                            Tags = new List<string> { "view", "calm", "elevated" },
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            City = "Sarajevo",
                            Details = "Modern loft style apartment.",
                            IsActiveOnApp = true,
                            IsAvailable = true,
                            IsRentingPerDay = true,
                            Location = "Kolodvorska 18",
                            Name = "Modern Loft",
                            NumberOfsquares = "62",
                            PricePerDay = 75.0,
                            PricePerMonth = 1800.0,
                            Tags = new List<string> { "loft", "stylish", "open" },
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            City = "Sarajevo",
                            Details = "Calm residential apartment.",
                            IsActiveOnApp = true,
                            IsAvailable = false,
                            IsRentingPerDay = true,
                            Location = "Grbavička 91",
                            Name = "Quiet Residential Flat",
                            NumberOfsquares = "50",
                            PricePerDay = 55.0,
                            PricePerMonth = 1350.0,
                            Tags = new List<string> { "quiet", "balanced", "comfortable" },
                            UserId = 3
                        },
                        new
                        {
                            Id = 6,
                            City = "Sarajevo",
                            Details = "Sunny apartment with open layout.",
                            IsActiveOnApp = true,
                            IsAvailable = true,
                            IsRentingPerDay = true,
                            Location = "Hamze Hume 5",
                            Name = "Sunny Apartment",
                            NumberOfsquares = "57",
                            PricePerDay = 68.0,
                            PricePerMonth = 1600.0,
                            Tags = new List<string> { "sunny", "warm", "airy" },
                            UserId = 1
                        },
                        new
                        {
                            Id = 7,
                            City = "Sarajevo",
                            Details = "Compact studio apartment.",
                            IsActiveOnApp = true,
                            IsAvailable = true,
                            IsRentingPerDay = true,
                            Location = "Logavina 23",
                            Name = "Compact Studio",
                            NumberOfsquares = "32",
                            PricePerDay = 45.0,
                            PricePerMonth = 1100.0,
                            Tags = new List<string> { "compact", "simple", "efficient" },
                            UserId = 3
                        },
                        new
                        {
                            Id = 8,
                            City = "Sarajevo",
                            Details = "Residence with panoramic city view.",
                            IsActiveOnApp = true,
                            IsAvailable = true,
                            IsRentingPerDay = true,
                            Location = "Skenderija 10",
                            Name = "Panorama Residence",
                            NumberOfsquares = "70",
                            PricePerDay = 80.0,
                            PricePerMonth = 1900.0,
                            Tags = new List<string> { "panorama", "exclusive", "bright" },
                            UserId = 1
                        },
                        new
                        {
                            Id = 9,
                            City = "Mostar",
                            Details = "Apartment near the river.",
                            IsActiveOnApp = true,
                            IsAvailable = true,
                            IsRentingPerDay = true,
                            Location = "Maršala Tita 14",
                            Name = "River Side Apartment",
                            NumberOfsquares = "58",
                            PricePerDay = 70.0,
                            PricePerMonth = 1650.0,
                            Tags = new List<string> { "river", "relaxing", "open" },
                            UserId = 3
                        },
                        new
                        {
                            Id = 10,
                            City = "Mostar",
                            Details = "Flat with a view of the Old Bridge.",
                            IsActiveOnApp = true,
                            IsAvailable = true,
                            IsRentingPerDay = true,
                            Location = "Rade Bitange 3",
                            Name = "Old Bridge View Flat",
                            NumberOfsquares = "65",
                            PricePerDay = 85.0,
                            PricePerMonth = 2000.0,
                            Tags = new List<string> { "iconic", "view", "historic" },
                            UserId = 1
                        },
                        new
                        {
                            Id = 11,
                            City = "Mostar",
                            Details = "Traditional stone apartment.",
                            IsActiveOnApp = true,
                            IsAvailable = false,
                            IsRentingPerDay = true,
                            Location = "Braće Fejića 27",
                            Name = "Stone House Apartment",
                            NumberOfsquares = "50",
                            PricePerDay = 60.0,
                            PricePerMonth = 1450.0,
                            Tags = new List<string> { "stone", "traditional", "cool" },
                            UserId = 3
                        },
                        new
                        {
                            Id = 12,
                            City = "Mostar",
                            Details = "Apartment with sunny terrace.",
                            IsActiveOnApp = true,
                            IsAvailable = true,
                            IsRentingPerDay = true,
                            Location = "Adema Buća 9",
                            Name = "Sunny Terrace Flat",
                            NumberOfsquares = "60",
                            PricePerDay = 75.0,
                            PricePerMonth = 1750.0,
                            Tags = new List<string> { "sunny", "terrace", "open" },
                            UserId = 1
                        },
                        new
                        {
                            Id = 13,
                            City = "Mostar",
                            Details = "Quiet apartment in city center.",
                            IsActiveOnApp = true,
                            IsAvailable = true,
                            IsRentingPerDay = true,
                            Location = "Kralja Tvrtka 6",
                            Name = "Quiet Center Apartment",
                            NumberOfsquares = "54",
                            PricePerDay = 65.0,
                            PricePerMonth = 1550.0,
                            Tags = new List<string> { "quiet", "central", "comfortable" },
                            UserId = 3
                        },
                        new
                        {
                            Id = 14,
                            City = "Mostar",
                            Details = "Minimalist apartment.",
                            IsActiveOnApp = true,
                            IsAvailable = true,
                            IsRentingPerDay = true,
                            Location = "Splitska 22",
                            Name = "Minimal Flat",
                            NumberOfsquares = "45",
                            PricePerDay = 55.0,
                            PricePerMonth = 1300.0,
                            Tags = new List<string> { "minimal", "clean", "simple" },
                            UserId = 1
                        },
                        new
                        {
                            Id = 15,
                            City = "Mostar",
                            Details = "Warm and relaxed living space.",
                            IsActiveOnApp = true,
                            IsAvailable = true,
                            IsRentingPerDay = true,
                            Location = "Put Mladih Muslimana 4",
                            Name = "Evening Light Apartment",
                            NumberOfsquares = "56",
                            PricePerDay = 68.0,
                            PricePerMonth = 1600.0,
                            Tags = new List<string> { "warm", "evening", "relaxed" },
                            UserId = 3
                        },
                        new
                        {
                            Id = 16,
                            City = "Tuzla",
                            Details = "Apartment in city center.",
                            IsActiveOnApp = true,
                            IsAvailable = true,
                            IsRentingPerDay = true,
                            Location = "Slatina 15",
                            Name = "City Center Apartment",
                            NumberOfsquares = "48",
                            PricePerDay = 50.0,
                            PricePerMonth = 1200.0,
                            Tags = new List<string> { "central", "balanced", "urban" },
                            UserId = 1
                        },
                        new
                        {
                            Id = 17,
                            City = "Tuzla",
                            Details = "Flat near salt lakes.",
                            IsActiveOnApp = true,
                            IsAvailable = true,
                            IsRentingPerDay = true,
                            Location = "Turalibegova 8",
                            Name = "Salt Lake View Flat",
                            NumberOfsquares = "55",
                            PricePerDay = 65.0,
                            PricePerMonth = 1500.0,
                            Tags = new List<string> { "lake", "fresh", "open" },
                            UserId = 3
                        },
                        new
                        {
                            Id = 18,
                            City = "Tuzla",
                            Details = "Studio in a quiet area.",
                            IsActiveOnApp = true,
                            IsAvailable = true,
                            IsRentingPerDay = true,
                            Location = "Batva 21",
                            Name = "Quiet Residential Studio",
                            NumberOfsquares = "30",
                            PricePerDay = 40.0,
                            PricePerMonth = 950.0,
                            Tags = new List<string> { "quiet", "compact", "simple" },
                            UserId = 1
                        },
                        new
                        {
                            Id = 19,
                            City = "Tuzla",
                            Details = "Modern city flat.",
                            IsActiveOnApp = true,
                            IsAvailable = true,
                            IsRentingPerDay = true,
                            Location = "Krečka 33",
                            Name = "Modern Flat",
                            NumberOfsquares = "50",
                            PricePerDay = 55.0,
                            PricePerMonth = 1300.0,
                            Tags = new List<string> { "modern", "clean", "bright" },
                            UserId = 3
                        },
                        new
                        {
                            Id = 20,
                            City = "Tuzla",
                            Details = "Spacious apartment for families.",
                            IsActiveOnApp = true,
                            IsAvailable = false,
                            IsRentingPerDay = true,
                            Location = "Brčanska Malta 12",
                            Name = "Family Apartment",
                            NumberOfsquares = "62",
                            PricePerDay = 60.0,
                            PricePerMonth = 1400.0,
                            Tags = new List<string> { "family", "comfortable", "spacious" },
                            UserId = 1
                        },
                        new
                        {
                            Id = 21,
                            City = "Tuzla",
                            Details = "Flat with great sunlight.",
                            IsActiveOnApp = true,
                            IsAvailable = true,
                            IsRentingPerDay = true,
                            Location = "Stupine A2",
                            Name = "Sunlit Flat",
                            NumberOfsquares = "53",
                            PricePerDay = 58.0,
                            PricePerMonth = 1350.0,
                            Tags = new List<string> { "sunny", "open", "warm" },
                            UserId = 3
                        },
                        new
                        {
                            Id = 22,
                            City = "Tuzla",
                            Details = "Calm and balanced apartment.",
                            IsActiveOnApp = true,
                            IsAvailable = true,
                            IsRentingPerDay = true,
                            Location = "Irac 6",
                            Name = "Calm Living Space",
                            NumberOfsquares = "49",
                            PricePerDay = 52.0,
                            PricePerMonth = 1250.0,
                            Tags = new List<string> { "calm", "balanced", "quiet" },
                            UserId = 1
                        },
                        new
                        {
                            Id = 23,
                            City = "Banja Luka",
                            Details = "Urban loft in city center.",
                            IsActiveOnApp = true,
                            IsAvailable = true,
                            IsRentingPerDay = true,
                            Location = "Kralja Petra I Karađorđevića 19",
                            Name = "City Loft",
                            NumberOfsquares = "60",
                            PricePerDay = 70.0,
                            PricePerMonth = 1650.0,
                            Tags = new List<string> { "loft", "urban", "creative" },
                            UserId = 3
                        },
                        new
                        {
                            Id = 24,
                            City = "Banja Luka",
                            Details = "Apartment near river walk.",
                            IsActiveOnApp = true,
                            IsAvailable = true,
                            IsRentingPerDay = true,
                            Location = "Obala Stepe Stepanovića 7",
                            Name = "River Walk Apartment",
                            NumberOfsquares = "58",
                            PricePerDay = 75.0,
                            PricePerMonth = 1750.0,
                            Tags = new List<string> { "river", "walkable", "fresh" },
                            UserId = 1
                        },
                        new
                        {
                            Id = 25,
                            City = "Banja Luka",
                            Details = "Minimalist residence.",
                            IsActiveOnApp = true,
                            IsAvailable = true,
                            IsRentingPerDay = true,
                            Location = "Cara Dušana 41",
                            Name = "Minimal Residence",
                            NumberOfsquares = "47",
                            PricePerDay = 55.0,
                            PricePerMonth = 1300.0,
                            Tags = new List<string> { "minimal", "clean", "simple" },
                            UserId = 3
                        },
                        new
                        {
                            Id = 26,
                            City = "Banja Luka",
                            Details = "Family-friendly city home.",
                            IsActiveOnApp = true,
                            IsAvailable = false,
                            IsRentingPerDay = true,
                            Location = "Bulevar Vojvode Stepe 88",
                            Name = "Family City Home",
                            NumberOfsquares = "64",
                            PricePerDay = 65.0,
                            PricePerMonth = 1550.0,
                            Tags = new List<string> { "family", "balanced", "comfortable" },
                            UserId = 1
                        },
                        new
                        {
                            Id = 27,
                            City = "Banja Luka",
                            Details = "Bright compact studio.",
                            IsActiveOnApp = true,
                            IsAvailable = true,
                            IsRentingPerDay = true,
                            Location = "Gundulićeva 10",
                            Name = "Bright Studio",
                            NumberOfsquares = "33",
                            PricePerDay = 45.0,
                            PricePerMonth = 1050.0,
                            Tags = new List<string> { "bright", "compact", "efficient" },
                            UserId = 3
                        },
                        new
                        {
                            Id = 28,
                            City = "Banja Luka",
                            Details = "Flat with panoramic view.",
                            IsActiveOnApp = true,
                            IsAvailable = true,
                            IsRentingPerDay = true,
                            Location = "Kninska 25",
                            Name = "Panorama Flat",
                            NumberOfsquares = "68",
                            PricePerDay = 78.0,
                            PricePerMonth = 1850.0,
                            Tags = new List<string> { "panorama", "open", "elevated" },
                            UserId = 1
                        },
                        new
                        {
                            Id = 29,
                            City = "Banja Luka",
                            Details = "Quiet corner apartment.",
                            IsActiveOnApp = true,
                            IsAvailable = true,
                            IsRentingPerDay = true,
                            Location = "Solunska 3",
                            Name = "Quiet Corner Apartment",
                            NumberOfsquares = "46",
                            PricePerDay = 50.0,
                            PricePerMonth = 1200.0,
                            Tags = new List<string> { "quiet", "corner", "calm" },
                            UserId = 3
                        },
                        new
                        {
                            Id = 30,
                            City = "Banja Luka",
                            Details = "Elegant flat in urban area.",
                            IsActiveOnApp = true,
                            IsAvailable = true,
                            IsRentingPerDay = true,
                            Location = "Vase Pelagića 17",
                            Name = "Elegant City Flat",
                            NumberOfsquares = "61",
                            PricePerDay = 72.0,
                            PricePerMonth = 1700.0,
                            Tags = new List<string> { "elegant", "stylish", "urban" },
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Rentify.Services.Database.PropertyImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsMain")
                        .HasColumnType("boolean");

                    b.Property<int>("PropertyId")
                        .HasColumnType("integer");

                    b.Property<string>("PropertyImg")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("PropertiesImage");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsMain = true,
                            PropertyId = 1,
                            PropertyImg = "https://picsum.photos/seed/property-1-1/900/600"
                        },
                        new
                        {
                            Id = 2,
                            IsMain = false,
                            PropertyId = 1,
                            PropertyImg = "https://picsum.photos/seed/property-1-2/900/600"
                        },
                        new
                        {
                            Id = 3,
                            IsMain = false,
                            PropertyId = 1,
                            PropertyImg = "https://picsum.photos/seed/property-1-3/900/600"
                        },
                        new
                        {
                            Id = 4,
                            IsMain = false,
                            PropertyId = 1,
                            PropertyImg = "https://picsum.photos/seed/property-1-4/900/600"
                        },
                        new
                        {
                            Id = 5,
                            IsMain = true,
                            PropertyId = 2,
                            PropertyImg = "https://picsum.photos/seed/property-2-1/900/600"
                        },
                        new
                        {
                            Id = 6,
                            IsMain = false,
                            PropertyId = 2,
                            PropertyImg = "https://picsum.photos/seed/property-2-2/900/600"
                        },
                        new
                        {
                            Id = 7,
                            IsMain = false,
                            PropertyId = 2,
                            PropertyImg = "https://picsum.photos/seed/property-2-3/900/600"
                        },
                        new
                        {
                            Id = 8,
                            IsMain = false,
                            PropertyId = 2,
                            PropertyImg = "https://picsum.photos/seed/property-2-4/900/600"
                        },
                        new
                        {
                            Id = 9,
                            IsMain = true,
                            PropertyId = 3,
                            PropertyImg = "https://picsum.photos/seed/property-3-1/900/600"
                        },
                        new
                        {
                            Id = 10,
                            IsMain = false,
                            PropertyId = 3,
                            PropertyImg = "https://picsum.photos/seed/property-3-2/900/600"
                        },
                        new
                        {
                            Id = 11,
                            IsMain = false,
                            PropertyId = 3,
                            PropertyImg = "https://picsum.photos/seed/property-3-3/900/600"
                        },
                        new
                        {
                            Id = 12,
                            IsMain = false,
                            PropertyId = 3,
                            PropertyImg = "https://picsum.photos/seed/property-3-4/900/600"
                        },
                        new
                        {
                            Id = 13,
                            IsMain = true,
                            PropertyId = 4,
                            PropertyImg = "https://picsum.photos/seed/property-4-1/900/600"
                        },
                        new
                        {
                            Id = 14,
                            IsMain = false,
                            PropertyId = 4,
                            PropertyImg = "https://picsum.photos/seed/property-4-2/900/600"
                        },
                        new
                        {
                            Id = 15,
                            IsMain = false,
                            PropertyId = 4,
                            PropertyImg = "https://picsum.photos/seed/property-4-3/900/600"
                        },
                        new
                        {
                            Id = 16,
                            IsMain = false,
                            PropertyId = 4,
                            PropertyImg = "https://picsum.photos/seed/property-4-4/900/600"
                        },
                        new
                        {
                            Id = 17,
                            IsMain = true,
                            PropertyId = 5,
                            PropertyImg = "https://picsum.photos/seed/property-5-1/900/600"
                        },
                        new
                        {
                            Id = 18,
                            IsMain = false,
                            PropertyId = 5,
                            PropertyImg = "https://picsum.photos/seed/property-5-2/900/600"
                        },
                        new
                        {
                            Id = 19,
                            IsMain = false,
                            PropertyId = 5,
                            PropertyImg = "https://picsum.photos/seed/property-5-3/900/600"
                        },
                        new
                        {
                            Id = 20,
                            IsMain = false,
                            PropertyId = 5,
                            PropertyImg = "https://picsum.photos/seed/property-5-4/900/600"
                        },
                        new
                        {
                            Id = 21,
                            IsMain = true,
                            PropertyId = 6,
                            PropertyImg = "https://picsum.photos/seed/property-6-1/900/600"
                        },
                        new
                        {
                            Id = 22,
                            IsMain = false,
                            PropertyId = 6,
                            PropertyImg = "https://picsum.photos/seed/property-6-2/900/600"
                        },
                        new
                        {
                            Id = 23,
                            IsMain = false,
                            PropertyId = 6,
                            PropertyImg = "https://picsum.photos/seed/property-6-3/900/600"
                        },
                        new
                        {
                            Id = 24,
                            IsMain = false,
                            PropertyId = 6,
                            PropertyImg = "https://picsum.photos/seed/property-6-4/900/600"
                        },
                        new
                        {
                            Id = 25,
                            IsMain = true,
                            PropertyId = 7,
                            PropertyImg = "https://picsum.photos/seed/property-7-1/900/600"
                        },
                        new
                        {
                            Id = 26,
                            IsMain = false,
                            PropertyId = 7,
                            PropertyImg = "https://picsum.photos/seed/property-7-2/900/600"
                        },
                        new
                        {
                            Id = 27,
                            IsMain = false,
                            PropertyId = 7,
                            PropertyImg = "https://picsum.photos/seed/property-7-3/900/600"
                        },
                        new
                        {
                            Id = 28,
                            IsMain = false,
                            PropertyId = 7,
                            PropertyImg = "https://picsum.photos/seed/property-7-4/900/600"
                        },
                        new
                        {
                            Id = 29,
                            IsMain = true,
                            PropertyId = 8,
                            PropertyImg = "https://picsum.photos/seed/property-8-1/900/600"
                        },
                        new
                        {
                            Id = 30,
                            IsMain = false,
                            PropertyId = 8,
                            PropertyImg = "https://picsum.photos/seed/property-8-2/900/600"
                        },
                        new
                        {
                            Id = 31,
                            IsMain = false,
                            PropertyId = 8,
                            PropertyImg = "https://picsum.photos/seed/property-8-3/900/600"
                        },
                        new
                        {
                            Id = 32,
                            IsMain = false,
                            PropertyId = 8,
                            PropertyImg = "https://picsum.photos/seed/property-8-4/900/600"
                        },
                        new
                        {
                            Id = 33,
                            IsMain = true,
                            PropertyId = 9,
                            PropertyImg = "https://picsum.photos/seed/property-9-1/900/600"
                        },
                        new
                        {
                            Id = 34,
                            IsMain = false,
                            PropertyId = 9,
                            PropertyImg = "https://picsum.photos/seed/property-9-2/900/600"
                        },
                        new
                        {
                            Id = 35,
                            IsMain = false,
                            PropertyId = 9,
                            PropertyImg = "https://picsum.photos/seed/property-9-3/900/600"
                        },
                        new
                        {
                            Id = 36,
                            IsMain = false,
                            PropertyId = 9,
                            PropertyImg = "https://picsum.photos/seed/property-9-4/900/600"
                        },
                        new
                        {
                            Id = 37,
                            IsMain = true,
                            PropertyId = 10,
                            PropertyImg = "https://picsum.photos/seed/property-10-1/900/600"
                        },
                        new
                        {
                            Id = 38,
                            IsMain = false,
                            PropertyId = 10,
                            PropertyImg = "https://picsum.photos/seed/property-10-2/900/600"
                        },
                        new
                        {
                            Id = 39,
                            IsMain = false,
                            PropertyId = 10,
                            PropertyImg = "https://picsum.photos/seed/property-10-3/900/600"
                        },
                        new
                        {
                            Id = 40,
                            IsMain = false,
                            PropertyId = 10,
                            PropertyImg = "https://picsum.photos/seed/property-10-4/900/600"
                        },
                        new
                        {
                            Id = 41,
                            IsMain = true,
                            PropertyId = 11,
                            PropertyImg = "https://picsum.photos/seed/property-11-1/900/600"
                        },
                        new
                        {
                            Id = 42,
                            IsMain = false,
                            PropertyId = 11,
                            PropertyImg = "https://picsum.photos/seed/property-11-2/900/600"
                        },
                        new
                        {
                            Id = 43,
                            IsMain = false,
                            PropertyId = 11,
                            PropertyImg = "https://picsum.photos/seed/property-11-3/900/600"
                        },
                        new
                        {
                            Id = 44,
                            IsMain = false,
                            PropertyId = 11,
                            PropertyImg = "https://picsum.photos/seed/property-11-4/900/600"
                        },
                        new
                        {
                            Id = 45,
                            IsMain = true,
                            PropertyId = 12,
                            PropertyImg = "https://picsum.photos/seed/property-12-1/900/600"
                        },
                        new
                        {
                            Id = 46,
                            IsMain = false,
                            PropertyId = 12,
                            PropertyImg = "https://picsum.photos/seed/property-12-2/900/600"
                        },
                        new
                        {
                            Id = 47,
                            IsMain = false,
                            PropertyId = 12,
                            PropertyImg = "https://picsum.photos/seed/property-12-3/900/600"
                        },
                        new
                        {
                            Id = 48,
                            IsMain = false,
                            PropertyId = 12,
                            PropertyImg = "https://picsum.photos/seed/property-12-4/900/600"
                        },
                        new
                        {
                            Id = 49,
                            IsMain = true,
                            PropertyId = 13,
                            PropertyImg = "https://picsum.photos/seed/property-13-1/900/600"
                        },
                        new
                        {
                            Id = 50,
                            IsMain = false,
                            PropertyId = 13,
                            PropertyImg = "https://picsum.photos/seed/property-13-2/900/600"
                        },
                        new
                        {
                            Id = 51,
                            IsMain = false,
                            PropertyId = 13,
                            PropertyImg = "https://picsum.photos/seed/property-13-3/900/600"
                        },
                        new
                        {
                            Id = 52,
                            IsMain = false,
                            PropertyId = 13,
                            PropertyImg = "https://picsum.photos/seed/property-13-4/900/600"
                        },
                        new
                        {
                            Id = 53,
                            IsMain = true,
                            PropertyId = 14,
                            PropertyImg = "https://picsum.photos/seed/property-14-1/900/600"
                        },
                        new
                        {
                            Id = 54,
                            IsMain = false,
                            PropertyId = 14,
                            PropertyImg = "https://picsum.photos/seed/property-14-2/900/600"
                        },
                        new
                        {
                            Id = 55,
                            IsMain = false,
                            PropertyId = 14,
                            PropertyImg = "https://picsum.photos/seed/property-14-3/900/600"
                        },
                        new
                        {
                            Id = 56,
                            IsMain = false,
                            PropertyId = 14,
                            PropertyImg = "https://picsum.photos/seed/property-14-4/900/600"
                        },
                        new
                        {
                            Id = 57,
                            IsMain = true,
                            PropertyId = 15,
                            PropertyImg = "https://picsum.photos/seed/property-15-1/900/600"
                        },
                        new
                        {
                            Id = 58,
                            IsMain = false,
                            PropertyId = 15,
                            PropertyImg = "https://picsum.photos/seed/property-15-2/900/600"
                        },
                        new
                        {
                            Id = 59,
                            IsMain = false,
                            PropertyId = 15,
                            PropertyImg = "https://picsum.photos/seed/property-15-3/900/600"
                        },
                        new
                        {
                            Id = 60,
                            IsMain = false,
                            PropertyId = 15,
                            PropertyImg = "https://picsum.photos/seed/property-15-4/900/600"
                        },
                        new
                        {
                            Id = 61,
                            IsMain = true,
                            PropertyId = 16,
                            PropertyImg = "https://picsum.photos/seed/property-16-1/900/600"
                        },
                        new
                        {
                            Id = 62,
                            IsMain = false,
                            PropertyId = 16,
                            PropertyImg = "https://picsum.photos/seed/property-16-2/900/600"
                        },
                        new
                        {
                            Id = 63,
                            IsMain = false,
                            PropertyId = 16,
                            PropertyImg = "https://picsum.photos/seed/property-16-3/900/600"
                        },
                        new
                        {
                            Id = 64,
                            IsMain = false,
                            PropertyId = 16,
                            PropertyImg = "https://picsum.photos/seed/property-16-4/900/600"
                        },
                        new
                        {
                            Id = 65,
                            IsMain = true,
                            PropertyId = 17,
                            PropertyImg = "https://picsum.photos/seed/property-17-1/900/600"
                        },
                        new
                        {
                            Id = 66,
                            IsMain = false,
                            PropertyId = 17,
                            PropertyImg = "https://picsum.photos/seed/property-17-2/900/600"
                        },
                        new
                        {
                            Id = 67,
                            IsMain = false,
                            PropertyId = 17,
                            PropertyImg = "https://picsum.photos/seed/property-17-3/900/600"
                        },
                        new
                        {
                            Id = 68,
                            IsMain = false,
                            PropertyId = 17,
                            PropertyImg = "https://picsum.photos/seed/property-17-4/900/600"
                        },
                        new
                        {
                            Id = 69,
                            IsMain = true,
                            PropertyId = 18,
                            PropertyImg = "https://picsum.photos/seed/property-18-1/900/600"
                        },
                        new
                        {
                            Id = 70,
                            IsMain = false,
                            PropertyId = 18,
                            PropertyImg = "https://picsum.photos/seed/property-18-2/900/600"
                        },
                        new
                        {
                            Id = 71,
                            IsMain = false,
                            PropertyId = 18,
                            PropertyImg = "https://picsum.photos/seed/property-18-3/900/600"
                        },
                        new
                        {
                            Id = 72,
                            IsMain = false,
                            PropertyId = 18,
                            PropertyImg = "https://picsum.photos/seed/property-18-4/900/600"
                        },
                        new
                        {
                            Id = 73,
                            IsMain = true,
                            PropertyId = 19,
                            PropertyImg = "https://picsum.photos/seed/property-19-1/900/600"
                        },
                        new
                        {
                            Id = 74,
                            IsMain = false,
                            PropertyId = 19,
                            PropertyImg = "https://picsum.photos/seed/property-19-2/900/600"
                        },
                        new
                        {
                            Id = 75,
                            IsMain = false,
                            PropertyId = 19,
                            PropertyImg = "https://picsum.photos/seed/property-19-3/900/600"
                        },
                        new
                        {
                            Id = 76,
                            IsMain = false,
                            PropertyId = 19,
                            PropertyImg = "https://picsum.photos/seed/property-19-4/900/600"
                        },
                        new
                        {
                            Id = 77,
                            IsMain = true,
                            PropertyId = 20,
                            PropertyImg = "https://picsum.photos/seed/property-20-1/900/600"
                        },
                        new
                        {
                            Id = 78,
                            IsMain = false,
                            PropertyId = 20,
                            PropertyImg = "https://picsum.photos/seed/property-20-2/900/600"
                        },
                        new
                        {
                            Id = 79,
                            IsMain = false,
                            PropertyId = 20,
                            PropertyImg = "https://picsum.photos/seed/property-20-3/900/600"
                        },
                        new
                        {
                            Id = 80,
                            IsMain = false,
                            PropertyId = 20,
                            PropertyImg = "https://picsum.photos/seed/property-20-4/900/600"
                        },
                        new
                        {
                            Id = 81,
                            IsMain = true,
                            PropertyId = 21,
                            PropertyImg = "https://picsum.photos/seed/property-21-1/900/600"
                        },
                        new
                        {
                            Id = 82,
                            IsMain = false,
                            PropertyId = 21,
                            PropertyImg = "https://picsum.photos/seed/property-21-2/900/600"
                        },
                        new
                        {
                            Id = 83,
                            IsMain = false,
                            PropertyId = 21,
                            PropertyImg = "https://picsum.photos/seed/property-21-3/900/600"
                        },
                        new
                        {
                            Id = 84,
                            IsMain = false,
                            PropertyId = 21,
                            PropertyImg = "https://picsum.photos/seed/property-21-4/900/600"
                        },
                        new
                        {
                            Id = 85,
                            IsMain = true,
                            PropertyId = 22,
                            PropertyImg = "https://picsum.photos/seed/property-22-1/900/600"
                        },
                        new
                        {
                            Id = 86,
                            IsMain = false,
                            PropertyId = 22,
                            PropertyImg = "https://picsum.photos/seed/property-22-2/900/600"
                        },
                        new
                        {
                            Id = 87,
                            IsMain = false,
                            PropertyId = 22,
                            PropertyImg = "https://picsum.photos/seed/property-22-3/900/600"
                        },
                        new
                        {
                            Id = 88,
                            IsMain = false,
                            PropertyId = 22,
                            PropertyImg = "https://picsum.photos/seed/property-22-4/900/600"
                        },
                        new
                        {
                            Id = 89,
                            IsMain = true,
                            PropertyId = 23,
                            PropertyImg = "https://picsum.photos/seed/property-23-1/900/600"
                        },
                        new
                        {
                            Id = 90,
                            IsMain = false,
                            PropertyId = 23,
                            PropertyImg = "https://picsum.photos/seed/property-23-2/900/600"
                        },
                        new
                        {
                            Id = 91,
                            IsMain = false,
                            PropertyId = 23,
                            PropertyImg = "https://picsum.photos/seed/property-23-3/900/600"
                        },
                        new
                        {
                            Id = 92,
                            IsMain = false,
                            PropertyId = 23,
                            PropertyImg = "https://picsum.photos/seed/property-23-4/900/600"
                        },
                        new
                        {
                            Id = 93,
                            IsMain = true,
                            PropertyId = 24,
                            PropertyImg = "https://picsum.photos/seed/property-24-1/900/600"
                        },
                        new
                        {
                            Id = 94,
                            IsMain = false,
                            PropertyId = 24,
                            PropertyImg = "https://picsum.photos/seed/property-24-2/900/600"
                        },
                        new
                        {
                            Id = 95,
                            IsMain = false,
                            PropertyId = 24,
                            PropertyImg = "https://picsum.photos/seed/property-24-3/900/600"
                        },
                        new
                        {
                            Id = 96,
                            IsMain = false,
                            PropertyId = 24,
                            PropertyImg = "https://picsum.photos/seed/property-24-4/900/600"
                        },
                        new
                        {
                            Id = 97,
                            IsMain = true,
                            PropertyId = 25,
                            PropertyImg = "https://picsum.photos/seed/property-25-1/900/600"
                        },
                        new
                        {
                            Id = 98,
                            IsMain = false,
                            PropertyId = 25,
                            PropertyImg = "https://picsum.photos/seed/property-25-2/900/600"
                        },
                        new
                        {
                            Id = 99,
                            IsMain = false,
                            PropertyId = 25,
                            PropertyImg = "https://picsum.photos/seed/property-25-3/900/600"
                        },
                        new
                        {
                            Id = 100,
                            IsMain = false,
                            PropertyId = 25,
                            PropertyImg = "https://picsum.photos/seed/property-25-4/900/600"
                        },
                        new
                        {
                            Id = 101,
                            IsMain = true,
                            PropertyId = 26,
                            PropertyImg = "https://picsum.photos/seed/property-26-1/900/600"
                        },
                        new
                        {
                            Id = 102,
                            IsMain = false,
                            PropertyId = 26,
                            PropertyImg = "https://picsum.photos/seed/property-26-2/900/600"
                        },
                        new
                        {
                            Id = 103,
                            IsMain = false,
                            PropertyId = 26,
                            PropertyImg = "https://picsum.photos/seed/property-26-3/900/600"
                        },
                        new
                        {
                            Id = 104,
                            IsMain = false,
                            PropertyId = 26,
                            PropertyImg = "https://picsum.photos/seed/property-26-4/900/600"
                        },
                        new
                        {
                            Id = 105,
                            IsMain = true,
                            PropertyId = 27,
                            PropertyImg = "https://picsum.photos/seed/property-27-1/900/600"
                        },
                        new
                        {
                            Id = 106,
                            IsMain = false,
                            PropertyId = 27,
                            PropertyImg = "https://picsum.photos/seed/property-27-2/900/600"
                        },
                        new
                        {
                            Id = 107,
                            IsMain = false,
                            PropertyId = 27,
                            PropertyImg = "https://picsum.photos/seed/property-27-3/900/600"
                        },
                        new
                        {
                            Id = 108,
                            IsMain = false,
                            PropertyId = 27,
                            PropertyImg = "https://picsum.photos/seed/property-27-4/900/600"
                        },
                        new
                        {
                            Id = 109,
                            IsMain = true,
                            PropertyId = 28,
                            PropertyImg = "https://picsum.photos/seed/property-28-1/900/600"
                        },
                        new
                        {
                            Id = 110,
                            IsMain = false,
                            PropertyId = 28,
                            PropertyImg = "https://picsum.photos/seed/property-28-2/900/600"
                        },
                        new
                        {
                            Id = 111,
                            IsMain = false,
                            PropertyId = 28,
                            PropertyImg = "https://picsum.photos/seed/property-28-3/900/600"
                        },
                        new
                        {
                            Id = 112,
                            IsMain = false,
                            PropertyId = 28,
                            PropertyImg = "https://picsum.photos/seed/property-28-4/900/600"
                        },
                        new
                        {
                            Id = 113,
                            IsMain = true,
                            PropertyId = 29,
                            PropertyImg = "https://picsum.photos/seed/property-29-1/900/600"
                        },
                        new
                        {
                            Id = 114,
                            IsMain = false,
                            PropertyId = 29,
                            PropertyImg = "https://picsum.photos/seed/property-29-2/900/600"
                        },
                        new
                        {
                            Id = 115,
                            IsMain = false,
                            PropertyId = 29,
                            PropertyImg = "https://picsum.photos/seed/property-29-3/900/600"
                        },
                        new
                        {
                            Id = 116,
                            IsMain = false,
                            PropertyId = 29,
                            PropertyImg = "https://picsum.photos/seed/property-29-4/900/600"
                        },
                        new
                        {
                            Id = 117,
                            IsMain = true,
                            PropertyId = 30,
                            PropertyImg = "https://picsum.photos/seed/property-30-1/900/600"
                        },
                        new
                        {
                            Id = 118,
                            IsMain = false,
                            PropertyId = 30,
                            PropertyImg = "https://picsum.photos/seed/property-30-2/900/600"
                        },
                        new
                        {
                            Id = 119,
                            IsMain = false,
                            PropertyId = 30,
                            PropertyImg = "https://picsum.photos/seed/property-30-3/900/600"
                        },
                        new
                        {
                            Id = 120,
                            IsMain = false,
                            PropertyId = 30,
                            PropertyImg = "https://picsum.photos/seed/property-30-4/900/600"
                        });
                });

            modelBuilder.Entity("Rentify.Services.Database.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndDateOfRenting")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMonthly")
                        .HasColumnType("boolean");

                    b.Property<int>("PropertyId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartDateOfRenting")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsApproved = true,
                            IsMonthly = true,
                            PropertyId = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsApproved = true,
                            IsMonthly = true,
                            PropertyId = 2,
                            UserId = 4
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsApproved = true,
                            IsMonthly = true,
                            PropertyId = 4,
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsApproved = true,
                            IsMonthly = true,
                            PropertyId = 6,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndDateOfRenting = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsApproved = true,
                            IsMonthly = false,
                            PropertyId = 8,
                            StartDateOfRenting = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 2
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 2, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndDateOfRenting = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsApproved = true,
                            IsMonthly = false,
                            PropertyId = 10,
                            StartDateOfRenting = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 4
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 2, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndDateOfRenting = new DateTime(2026, 4, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsApproved = true,
                            IsMonthly = false,
                            PropertyId = 12,
                            StartDateOfRenting = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 2
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 2, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndDateOfRenting = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsApproved = true,
                            IsMonthly = false,
                            PropertyId = 14,
                            StartDateOfRenting = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 4
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsMonthly = true,
                            PropertyId = 16,
                            UserId = 2
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 2, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndDateOfRenting = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsMonthly = false,
                            PropertyId = 18,
                            StartDateOfRenting = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 4
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsMonthly = true,
                            PropertyId = 20,
                            UserId = 2
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 2, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndDateOfRenting = new DateTime(2026, 5, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsMonthly = false,
                            PropertyId = 22,
                            StartDateOfRenting = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 4
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 2, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsApproved = false,
                            IsMonthly = true,
                            PropertyId = 24,
                            UserId = 2
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndDateOfRenting = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsApproved = false,
                            IsMonthly = false,
                            PropertyId = 26,
                            StartDateOfRenting = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 4
                        });
                });

            modelBuilder.Entity("Rentify.Services.Database.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PropertyId")
                        .HasColumnType("integer");

                    b.Property<int>("StarRate")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Odličan stan, čisto i uredno. Lokacija savršena.",
                            PropertyId = 1,
                            StarRate = 5,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Predivan pogled i jako ljubazan vlasnik.",
                            PropertyId = 8,
                            StarRate = 5,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Comment = "Stan je moderan i komforan, preporuka.",
                            PropertyId = 4,
                            StarRate = 4,
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            Comment = "Solidno iskustvo, sve je bilo korektno.",
                            PropertyId = 12,
                            StarRate = 4,
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            Comment = "Lijep ambijent i mirna lokacija.",
                            PropertyId = 2,
                            StarRate = 4,
                            UserId = 4
                        },
                        new
                        {
                            Id = 6,
                            Comment = "Stan je bio uredan, ali može bolje održavanje.",
                            PropertyId = 6,
                            StarRate = 3,
                            UserId = 4
                        },
                        new
                        {
                            Id = 7,
                            Comment = "Top lokacija u Mostaru, pogled fantastičan!",
                            PropertyId = 10,
                            StarRate = 5,
                            UserId = 4
                        },
                        new
                        {
                            Id = 8,
                            Comment = "Minimalistički stan, vrlo prijatan boravak.",
                            PropertyId = 14,
                            StarRate = 4,
                            UserId = 4
                        },
                        new
                        {
                            Id = 9,
                            Comment = "Praktičan stan u centru Tuzle.",
                            PropertyId = 16,
                            StarRate = 4,
                            UserId = 2
                        },
                        new
                        {
                            Id = 10,
                            Comment = "Loft je unikatan i jako udoban.",
                            PropertyId = 23,
                            StarRate = 5,
                            UserId = 4
                        },
                        new
                        {
                            Id = 11,
                            Comment = "Stan uz rijeku, veoma ugodno iskustvo.",
                            PropertyId = 24,
                            StarRate = 4,
                            UserId = 2
                        },
                        new
                        {
                            Id = 12,
                            Comment = "Panoramski pogled vrijedi svake marke.",
                            PropertyId = 28,
                            StarRate = 5,
                            UserId = 4
                        });
                });

            modelBuilder.Entity("Rentify.Services.Database.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 1, 13, 30, 5, 54, DateTimeKind.Utc).AddTicks(3466),
                            Description = "Standardni korisnik aplikacije",
                            IsActive = true,
                            Name = "Korisnik"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 3, 1, 13, 30, 5, 54, DateTimeKind.Utc).AddTicks(3469),
                            Description = "Vlasnik nekretnina koji može upravljati objektima",
                            IsActive = true,
                            Name = "Vlasnik"
                        });
                });

            modelBuilder.Entity("Rentify.Services.Database.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLoggingFirstTime")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVlasnik")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<List<string>>("PreferedTagsIfNoReservations")
                        .HasColumnType("text[]");

                    b.Property<string>("UserImage")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 1, 13, 30, 5, 54, DateTimeKind.Utc).AddTicks(3713),
                            Email = "owner.testni@gmail.com",
                            FirstName = "Marko",
                            IsActive = true,
                            IsLoggingFirstTime = false,
                            IsVlasnik = true,
                            LastName = "Petrov",
                            PasswordHash = "riSFqAsw2v7BCXEwg7ykYH7VyKpRuzPJ9CBLIFSG+/sSYQPZZ021kNtsOdlcdSTm7AS8zP9lnr2TPy/ChrxJ5w==",
                            PasswordSalt = "dtPtHblMAZ8l6+4BchcuDk1g64FWur5MLbufJaM8CEs6Kvs7IYKD1YN0GDCBpi1QY3XGOzcJ07oxeWOFT5QuoeQoheuKkcz6UJCnG13/pL45KL3M3HaL4VHAH/sYt6au3elk4bzUjOZE6d+yssGRz/HIiWhtv8gybb641x6EZRE=",
                            Username = "owner1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 3, 1, 13, 30, 5, 54, DateTimeKind.Utc).AddTicks(3723),
                            Email = "ivana.kovac@rentify.dev",
                            FirstName = "Ivana",
                            IsActive = true,
                            IsLoggingFirstTime = false,
                            IsVlasnik = false,
                            LastName = "Kovac",
                            PasswordHash = "riSFqAsw2v7BCXEwg7ykYH7VyKpRuzPJ9CBLIFSG+/sSYQPZZ021kNtsOdlcdSTm7AS8zP9lnr2TPy/ChrxJ5w==",
                            PasswordSalt = "dtPtHblMAZ8l6+4BchcuDk1g64FWur5MLbufJaM8CEs6Kvs7IYKD1YN0GDCBpi1QY3XGOzcJ07oxeWOFT5QuoeQoheuKkcz6UJCnG13/pL45KL3M3HaL4VHAH/sYt6au3elk4bzUjOZE6d+yssGRz/HIiWhtv8gybb641x6EZRE=",
                            Username = "user1"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 3, 1, 13, 30, 5, 54, DateTimeKind.Utc).AddTicks(3725),
                            Email = "nikola.jovic@rentify.dev",
                            FirstName = "Nikola",
                            IsActive = true,
                            IsLoggingFirstTime = false,
                            IsVlasnik = true,
                            LastName = "Jovic",
                            PasswordHash = "riSFqAsw2v7BCXEwg7ykYH7VyKpRuzPJ9CBLIFSG+/sSYQPZZ021kNtsOdlcdSTm7AS8zP9lnr2TPy/ChrxJ5w==",
                            PasswordSalt = "dtPtHblMAZ8l6+4BchcuDk1g64FWur5MLbufJaM8CEs6Kvs7IYKD1YN0GDCBpi1QY3XGOzcJ07oxeWOFT5QuoeQoheuKkcz6UJCnG13/pL45KL3M3HaL4VHAH/sYt6au3elk4bzUjOZE6d+yssGRz/HIiWhtv8gybb641x6EZRE=",
                            Username = "owner2"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 3, 1, 13, 30, 5, 54, DateTimeKind.Utc).AddTicks(3727),
                            Email = "amar.hodzic@rentify.dev",
                            FirstName = "Amar",
                            IsActive = true,
                            IsLoggingFirstTime = false,
                            IsVlasnik = false,
                            LastName = "Hodzic",
                            PasswordHash = "riSFqAsw2v7BCXEwg7ykYH7VyKpRuzPJ9CBLIFSG+/sSYQPZZ021kNtsOdlcdSTm7AS8zP9lnr2TPy/ChrxJ5w==",
                            PasswordSalt = "dtPtHblMAZ8l6+4BchcuDk1g64FWur5MLbufJaM8CEs6Kvs7IYKD1YN0GDCBpi1QY3XGOzcJ07oxeWOFT5QuoeQoheuKkcz6UJCnG13/pL45KL3M3HaL4VHAH/sYt6au3elk4bzUjOZE6d+yssGRz/HIiWhtv8gybb641x6EZRE=",
                            Username = "user2"
                        });
                });

            modelBuilder.Entity("Rentify.Services.Database.UserDeviceToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DeviceId")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId", "IsActive");

                    b.ToTable("UserDeviceTokens");
                });

            modelBuilder.Entity("Rentify.Services.Database.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateAssigned")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 2,
                            DateAssigned = new DateTime(2026, 3, 1, 13, 30, 5, 54, DateTimeKind.Utc).AddTicks(3755),
                            Id = 0
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 1,
                            DateAssigned = new DateTime(2026, 3, 1, 13, 30, 5, 54, DateTimeKind.Utc).AddTicks(3757),
                            Id = 0
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 2,
                            DateAssigned = new DateTime(2026, 3, 1, 13, 30, 5, 54, DateTimeKind.Utc).AddTicks(3758),
                            Id = 0
                        },
                        new
                        {
                            UserId = 4,
                            RoleId = 1,
                            DateAssigned = new DateTime(2026, 3, 1, 13, 30, 5, 54, DateTimeKind.Utc).AddTicks(3759),
                            Id = 0
                        });
                });

            modelBuilder.Entity("Rentify.Services.Database.Appointment", b =>
                {
                    b.HasOne("Rentify.Services.Database.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rentify.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Rentify.Services.Database.Payment", b =>
                {
                    b.HasOne("Rentify.Services.Database.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rentify.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Rentify.Services.Database.Property", b =>
                {
                    b.HasOne("Rentify.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Rentify.Services.Database.PropertyImage", b =>
                {
                    b.HasOne("Rentify.Services.Database.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("Rentify.Services.Database.Reservation", b =>
                {
                    b.HasOne("Rentify.Services.Database.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rentify.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Rentify.Services.Database.Review", b =>
                {
                    b.HasOne("Rentify.Services.Database.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rentify.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Rentify.Services.Database.UserDeviceToken", b =>
                {
                    b.HasOne("Rentify.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Rentify.Services.Database.UserRole", b =>
                {
                    b.HasOne("Rentify.Services.Database.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rentify.Services.Database.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Rentify.Services.Database.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Rentify.Services.Database.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
